name: Build and Publish Docker Image

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - action.yml
      - .github/workflows/**
      - LICENSE
      - .gitignore
      - test/**
      - unit-tests.py

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Git SHA
        id: sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build the Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ steps.sha.outputs.sha_short }} .

      - name: Push the Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ steps.sha.outputs.sha_short }}
